package com.cropadvisory.engine;

/**
 * Encapsulates the Yield Estimation generated by the ML regression component.
 */
public class YieldPrediction {
    private double yieldTonsPerHa;
    private double totalYieldTons;
    private double fieldArea;
    private String areaUnit;
    private String modelName;
    private double r2Score;
    private double maeError;
    private String disclaimer;

    public YieldPrediction(double yieldTonsPerHa, double totalYieldTons, double fieldArea, String areaUnit, double r2Score, double maeError) {
        this.yieldTonsPerHa = yieldTonsPerHa;
        this.totalYieldTons = totalYieldTons;
        this.fieldArea = fieldArea;
        this.areaUnit = areaUnit;
        this.modelName = "Multiple Linear Regression Pipeline (Python ML Engine)";
        this.r2Score = r2Score;
        this.maeError = maeError;
        this.disclaimer = "Estimated value — actual yield may vary depending on field conditions, weather, crop management and other factors.";
    }

    public double getYieldTonsPerHa() { return yieldTonsPerHa; }
    public double getTotalYieldTons() { return totalYieldTons; }
    public double getFieldArea() { return fieldArea; }
    public String getAreaUnit() { return areaUnit; }
    public String getModelName() { return modelName; }
    public double getR2Score() { return r2Score; }
    public double getMaeError() { return maeError; }
    public String getDisclaimer() { return disclaimer; }
}
